### ISSUE TITLE
AlminPerfMarker should not throw error

### ISSUE THREAD

**Issue by azu** [almin/almin#310]
In sometimes, AlminPerfMarker throw an Error:

It come form `performance.measure` and mismatch status.
We want to improve this status.
```
AlminPerfMarker.js:37 Uncaught (in promise) DOMException: Failed to execute 'measure' on 'Performance': The mark 'almin::UseCase__1::UserCase#complete' does not exist.
    at AlminPerfMarker._this.markEnd (http://localhost:12011/static/js/bundle.js:12613:25)
    at AlminPerfMarker.../../node_modules/almin/lib/src/instrument/AlminPerfMarker.js.AlminPerfMarker.completeUseCaseExecute (http://localhost:12011/static/js/bundle.js:12689:14)
    at http://localhost:12011/static/js/bundle.js:9475:45
    at Dispatcher.onCompleteEachUseCase (http://localhost:12011/static/js/bundle.js:10300:17)
    at Dispatcher.../../node_modules/events/events.js.EventEmitter.emit (http://localhost:12011/static/js/bundle.js:14924:20)
    at Dispatcher.../../node_modules/almin/lib/src/Dispatcher.js.Dispatcher.dispatch (http://localhost:12011/static/js/bundle.js:9942:18)
    at UseCaseExecutorImpl.onDispatchOnUnitOfWork (http://localhost:12011/static/js/bundle.js:11753:30)
    at UseCaseExecutorImpl.../../node_modules/events/events.js.EventEmitter.emit (http://localhost:12011/static/js/bundle.js:14912:17)
    at UseCaseExecutorImpl.../../node_modules/almin/lib/src/Dispatcher.js.Dispatcher.dispatch (http://localhost:12011/static/js/bundle.js:9942:18)
    at UseCaseExecutorImpl.../../node_modules/almin/lib/src/UseCaseExecutor.js.UseCaseExecutorImpl.completeUseCase (http://localhost:12011/static/js/bundle.js:12264:14)
    at http://localhost:12011/static/js/bundle.js:12355:19
    at <anonymous>
```

It caused  by exection in UseCase#execute

![image](https://user-images.githubusercontent.com/19714/34465350-c12b40be-eeeb-11e7-99bb-6896f9baf3b6.png)

**Comment by azu** [comment]
Umm, We can not reproduce code in lastest version

**Comment by azu** [comment]
https://github.com/azu/searchive can reproce with latest version.
I'll investigate it.

**Comment by azu** [comment]
I figure out this issue.

Currently, A UseCase throw error in `UseCase#execute`.

- will execute
- throw error
- **Skip did execute**
- Complete execute

**did execute** is not called in this case.

This issue come from here.

- https://github.com/almin/almin/blob/192b83985366c54393197256a3c36e5ef35b8ff3/packages/almin/src/instrument/AlminPerfMarker.ts#L108-L120

**Comment by azu** [comment]
I think that **did execute** is always called.

- [UseCase LifeCycle · Almin](https://almin.js.org/docs/en/usecase-lifecycle.html "UseCase LifeCycle · Almin")

**Comment by azu** [comment]
| UseCase Status                    | Did  | Error | Complete |
| --------------------------------- | ---- | ----- | -------- |
| Sync Success                      | 1    | --    | 2        |
| Async Success                     | 1    | --    | 2        |
| Sync Error(Throw Erro in execute) | 2    | 1     | 3        |
| Async Error(Promise is rejected)  | 1    | 2     | 3        |

**Comment by azu** [comment]
| UseCase Type         | Will | Did  | Error | Complete | Return Promise                      |
| -------------------- | ---- | ---- | ----- | -------- | ----------------------------------- |
| Sync Success         | 1    | 2    | --    | 3        | resolve(then)                       |
| Async Success        | 1    | 2    | --    | 3        | resolve(then)                       |
| Sync Failure         | 1    | --    | 2     | 3        | reject(catch)                       |
| Async Failure        | 1    | 2    | 3     | 4        | reject(catch)                       |
| ShouldExecute: false | --   | --   | --    | --       | resolve(then) - prevent memory leak |

**Sync Failure**  did not called `didExecute`.

**Comment by azu** [comment]
![image](https://user-images.githubusercontent.com/19714/35218981-01ca6432-ffb4-11e7-916b-d7c507b8449c.png)
Show correct error in console.

OK, I've confirm that this issue is reoslved.
